export const browserFonts = [
  { name: 'Arial' },
  { name: 'Arial Black' },
  { name: 'Arial Narrow' },
  { name: 'Arial Rounded MT Bold' },
  { name: 'Avant Garde' },
  { name: 'Calibri' },
  { name: 'Candara' },
  { name: 'Century Gothic' },
  { name: 'Courier' },
  { name: 'Courier New' },
  { name: 'Franklin Gothic Medium' },
  { name: 'Futura' },
  { name: 'Geneva' },
  { name: 'Georgia' },
  { name: 'Gill Sans' },
  { name: 'Helvetica' },
  { name: 'Impact' },
  { name: 'Lucida Console' },
  { name: 'Lucida Grande' },
  { name: 'Lucida Sans Unicode' },
  { name: 'Microsoft Sans Serif' },
  { name: 'Monaco' },
  { name: 'Optima' },
  { name: 'Palatino' },
  { name: 'Palatino Linotype' },
  { name: 'Segoe UI' },
  { name: 'Tahoma' },
  { name: 'Times' },
  { name: 'Times New Roman' },
  { name: 'Trebuchet MS' },
  { name: 'Verdana' }
];
